/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package struts.FSM.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 01-07-2010
 * 
 * XDoclet definition:
 * @struts.form name="dataMovementForm"
 */
public class DataMovementForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** dataMoveName property */
	private String dataMoveName;

	/** funcProsId property */
	private String funcProsId;

	/** dataGroupId property */
	private String dataGroupId;

	/** dataMoveType property */
	private String dataMoveType;

	/** dataMoveDesp property */
	private String dataMoveDesp;

	/** id property */
	private String id;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the dataMoveName.
	 * @return String
	 */
	public String getDataMoveName() {
		return dataMoveName;
	}

	/** 
	 * Set the dataMoveName.
	 * @param dataMoveName The dataMoveName to set
	 */
	public void setDataMoveName(String dataMoveName) {
		this.dataMoveName = dataMoveName;
	}

	/** 
	 * Returns the funcProsId.
	 * @return String
	 */
	public String getFuncProsId() {
		return funcProsId;
	}

	/** 
	 * Set the funcProsId.
	 * @param funcProsId The funcProsId to set
	 */
	public void setFuncProsId(String funcProsId) {
		this.funcProsId = funcProsId;
	}

	/** 
	 * Returns the dataGroupId.
	 * @return String
	 */
	public String getDataGroupId() {
		return dataGroupId;
	}

	/** 
	 * Set the dataGroupId.
	 * @param dataGroupId The dataGroupId to set
	 */
	public void setDataGroupId(String dataGroupId) {
		this.dataGroupId = dataGroupId;
	}

	/** 
	 * Returns the dataMoveType.
	 * @return String
	 */
	public String getDataMoveType() {
		return dataMoveType;
	}

	/** 
	 * Set the dataMoveType.
	 * @param dataMoveType The dataMoveType to set
	 */
	public void setDataMoveType(String dataMoveType) {
		this.dataMoveType = dataMoveType;
	}

	/** 
	 * Returns the dataMoveDesp.
	 * @return String
	 */
	public String getDataMoveDesp() {
		return dataMoveDesp;
	}

	/** 
	 * Set the dataMoveDesp.
	 * @param dataMoveDesp The dataMoveDesp to set
	 */
	public void setDataMoveDesp(String dataMoveDesp) {
		this.dataMoveDesp = dataMoveDesp;
	}

	/** 
	 * Returns the id.
	 * @return String
	 */
	public String getId() {
		return id;
	}

	/** 
	 * Set the id.
	 * @param id The id to set
	 */
	public void setId(String id) {
		this.id = id;
	}
}