/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package struts.FSM.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 01-07-2010
 * 
 * XDoclet definition:
 * @struts.form name="dataGroupForm"
 */
public class DataGroupForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** interestObjId property */
	private String interestObjId;

	/** dataGroupName property */
	private String dataGroupName;

	/** dataGroupDesp property */
	private String dataGroupDesp;

	/** id property */
	private String id;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the interestObjId.
	 * @return String
	 */
	public String getInterestObjId() {
		return interestObjId;
	}

	/** 
	 * Set the interestObjId.
	 * @param interestObjId The interestObjId to set
	 */
	public void setInterestObjId(String interestObjId) {
		this.interestObjId = interestObjId;
	}

	/** 
	 * Returns the dataGroupName.
	 * @return String
	 */
	public String getDataGroupName() {
		return dataGroupName;
	}

	/** 
	 * Set the dataGroupName.
	 * @param dataGroupName The dataGroupName to set
	 */
	public void setDataGroupName(String dataGroupName) {
		this.dataGroupName = dataGroupName;
	}

	/** 
	 * Returns the dataGroupDesp.
	 * @return String
	 */
	public String getDataGroupDesp() {
		return dataGroupDesp;
	}

	/** 
	 * Set the dataGroupDesp.
	 * @param dataGroupDesp The dataGroupDesp to set
	 */
	public void setDataGroupDesp(String dataGroupDesp) {
		this.dataGroupDesp = dataGroupDesp;
	}

	/** 
	 * Returns the id.
	 * @return String
	 */
	public String getId() {
		return id;
	}

	/** 
	 * Set the id.
	 * @param id The id to set
	 */
	public void setId(String id) {
		this.id = id;
	}
}