/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package struts.FSM.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 01-07-2010
 * 
 * XDoclet definition:
 * @struts.form name="functionProcessInterestObjectForm"
 */
public class FunctionProcessInterestObjectForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** interestObjId property */
	private String[] interestObjId;

	/** funcProsId property */
	private String funcProsId;

	/** id property */
	private String id;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the interestObjId.
	 * @return String[]
	 */
	public String[] getInterestObjId() {
		return interestObjId;
	}

	/** 
	 * Set the interestObjId.
	 * @param interestObjId The interestObjId to set
	 */
	public void setInterestObjId(String[] interestObjId) {
		this.interestObjId = interestObjId;
	}

	/** 
	 * Returns the funcProsId.
	 * @return String
	 */
	public String getFuncProsId() {
		return funcProsId;
	}

	/** 
	 * Set the funcProsId.
	 * @param funcProsId The funcProsId to set
	 */
	public void setFuncProsId(String funcProsId) {
		this.funcProsId = funcProsId;
	}

	/** 
	 * Returns the id.
	 * @return String
	 */
	public String getId() {
		return id;
	}

	/** 
	 * Set the id.
	 * @param id The id to set
	 */
	public void setId(String id) {
		this.id = id;
	}
}