/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package struts.FSM.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 01-06-2010
 * 
 * XDoclet definition:
 * @struts.form name="addFunctionProcessForm"
 */
public class FunctionProcessForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** measureStatus property */
	private String measureStatus;

	/** peerCompId property */
	private String peerCompId;

	/** funcProsDesp property */
	private String funcProsDesp;

	/** funcProsName property */
	private String funcProsName;

	/** id property */
	private String id;
	
	private String mappingUserStatus;
	
	private String mappingEventStatus;
	
	private String mappingIOStatus;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the measureStatus.
	 * @return String
	 */
	public String getMeasureStatus() {
		return measureStatus;
	}

	/** 
	 * Set the measureStatus.
	 * @param measureStatus The measureStatus to set
	 */
	public void setMeasureStatus(String measureStatus) {
		this.measureStatus = measureStatus;
	}

	/** 
	 * Returns the peerCompId.
	 * @return String
	 */
	public String getPeerCompId() {
		return peerCompId;
	}

	/** 
	 * Set the peerCompId.
	 * @param peerCompId The peerCompId to set
	 */
	public void setPeerCompId(String peerCompId) {
		this.peerCompId = peerCompId;
	}

	/** 
	 * Returns the funcProsDesp.
	 * @return String
	 */
	public String getFuncProsDesp() {
		return funcProsDesp;
	}

	/** 
	 * Set the funcProsDesp.
	 * @param funcProsDesp The funcProsDesp to set
	 */
	public void setFuncProsDesp(String funcProsDesp) {
		this.funcProsDesp = funcProsDesp;
	}

	/** 
	 * Returns the funcProsName.
	 * @return String
	 */
	public String getFuncProsName() {
		return funcProsName;
	}

	/** 
	 * Set the funcProsName.
	 * @param funcProsName The funcProsName to set
	 */
	public void setFuncProsName(String funcProsName) {
		this.funcProsName = funcProsName;
	}

	/** 
	 * Returns the funcProsType.
	 * @return String
	 */

	/** 
	 * Returns the id.
	 * @return String
	 */
	public String getId() {
		return id;
	}

	/** 
	 * Set the id.
	 * @param id The id to set
	 */
	public void setId(String id) {
		this.id = id;
	}

	public String getMappingUserStatus() {
		return mappingUserStatus;
	}

	public void setMappingUserStatus(String mappingUserStatus) {
		this.mappingUserStatus = mappingUserStatus;
	}

	public String getMappingEventStatus() {
		return mappingEventStatus;
	}

	public void setMappingEventStatus(String mappingEventStatus) {
		this.mappingEventStatus = mappingEventStatus;
	}

	public String getMappingIOStatus() {
		return mappingIOStatus;
	}

	public void setMappingIOStatus(String mappingIOStatus) {
		this.mappingIOStatus = mappingIOStatus;
	}
}