/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package struts.FSM.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 01-06-2010
 * 
 * XDoclet definition:
 * @struts.form name="interestObjectForm"
 */
public class InterestObjectForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** interestObjName property */
	private String interestObjName;

	/** peerCompId property */
	private String peerCompId;

	/** interestObjDesp property */
	private String interestObjDesp;

	/** id property */
	private String id;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the interestObjName.
	 * @return String
	 */
	public String getInterestObjName() {
		return interestObjName;
	}

	/** 
	 * Set the interestObjName.
	 * @param interestObjName The interestObjName to set
	 */
	public void setInterestObjName(String interestObjName) {
		this.interestObjName = interestObjName;
	}

	/** 
	 * Returns the peerCompId.
	 * @return String
	 */
	public String getPeerCompId() {
		return peerCompId;
	}

	/** 
	 * Set the peerCompId.
	 * @param peerCompId The peerCompId to set
	 */
	public void setPeerCompId(String peerCompId) {
		this.peerCompId = peerCompId;
	}

	/** 
	 * Returns the interestObjDesp.
	 * @return String
	 */
	public String getInterestObjDesp() {
		return interestObjDesp;
	}

	/** 
	 * Set the interestObjDesp.
	 * @param interestObjDesp The interestObjDesp to set
	 */
	public void setInterestObjDesp(String interestObjDesp) {
		this.interestObjDesp = interestObjDesp;
	}

	/** 
	 * Returns the id.
	 * @return String
	 */
	public String getId() {
		return id;
	}

	/** 
	 * Set the id.
	 * @param id The id to set
	 */
	public void setId(String id) {
		this.id = id;
	}
}