/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package struts.FSM.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 04-25-2010
 * 
 * XDoclet definition:
 * @struts.form name="measurePurposeForm"
 */
public class MeasurePurposeForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** measurePurposeName property */
	private String measurePurposeName;

	/** productId property */
	private String productId;

	/** id property */
	private String id;

	/** measurePurposeDesp property */
	private String measurePurposeDesp;

	/** measure property */
	private String measure;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the measurePurposeName.
	 * @return String
	 */
	public String getMeasurePurposeName() {
		return measurePurposeName;
	}

	/** 
	 * Set the measurePurposeName.
	 * @param measurePurposeName The measurePurposeName to set
	 */
	public void setMeasurePurposeName(String measurePurposeName) {
		this.measurePurposeName = measurePurposeName;
	}

	/** 
	 * Returns the productId.
	 * @return String
	 */
	public String getProductId() {
		return productId;
	}

	/** 
	 * Set the productId.
	 * @param productId The productId to set
	 */
	public void setProductId(String productId) {
		this.productId = productId;
	}

	/** 
	 * Returns the id.
	 * @return String
	 */
	public String getId() {
		return id;
	}

	/** 
	 * Set the id.
	 * @param id The id to set
	 */
	public void setId(String id) {
		this.id = id;
	}

	/** 
	 * Returns the measurePurposeDesp.
	 * @return String
	 */
	public String getMeasurePurposeDesp() {
		return measurePurposeDesp;
	}

	/** 
	 * Set the measurePurposeDesp.
	 * @param measurePurposeDesp The measurePurposeDesp to set
	 */
	public void setMeasurePurposeDesp(String measurePurposeDesp) {
		this.measurePurposeDesp = measurePurposeDesp;
	}

	/** 
	 * Returns the measure.
	 * @return String
	 */
	public String getMeasure() {
		return measure;
	}

	/** 
	 * Set the measure.
	 * @param measure The measure to set
	 */
	public void setMeasure(String measure) {
		this.measure = measure;
	}
}