/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package struts.FSM.action;

import java.io.UnsupportedEncodingException;

import hibernate.FSM.FsmDataAttribute;
import hibernate.FSM.FsmDataGroup;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import net.sf.hibernate.HibernateException;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import business.FSM.MappingPhase;
import struts.FSM.form.DataAttributeForm;

/** 
 * MyEclipse Struts
 * Creation date: 01-07-2010
 * 
 * XDoclet definition:
 * @struts.action path="/addDataAttribute" name="dataAttributeForm" scope="request" validate="true"
 * @struts.action-forward name="success" path="/FSM/cosmicStandard/mapping/dataAttribute.jsp" contextRelative="true"
 * @struts.action-forward name="failure" path="/FSM/cosmicStandard/failure.jsp" contextRelative="true"
 */
public class AddDataAttributeAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 * @throws HibernateException 
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) throws HibernateException {
		DataAttributeForm dataAttributeForm = (DataAttributeForm) form;// TODO Auto-generated method stub
		MappingPhase mp = new MappingPhase();//业务层函数,对数据属性进行增删改查等操作
		FsmDataAttribute fda = new FsmDataAttribute();          //定义实体bean	
		Integer dataGroupId = new Integer(request.getParameter("dataGroupId")); 
	    Integer interestObjId = new Integer(request.getParameter("interestObjId")); 
		/*从form表单中获取DataAttribute信息,赋值给实体Bean*/
		String dataAttriName = null;
		String dataAttriDesp = null;
		try {
			dataAttriName = new String(dataAttributeForm.getDataAttriName().getBytes("ISO-8859-1"),"gb2312");
			dataAttriDesp = new String(dataAttributeForm.getDataAttriDesp().getBytes("ISO-8859-1"),"gb2312");
		} catch (UnsupportedEncodingException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		
		
		fda.setDataGroupId(new Integer(dataAttributeForm.getDataGroupId()));
		fda.setDataAttriName(dataAttriName);
		fda.setDataAttriDesp(dataAttriDesp);
		
		
		/*调用业务层,添加数据属性*/
		boolean result = mp.insertDataAttribute(fda);
		if(result=true){			
			 request.setAttribute("dataGroupId", dataGroupId);
			 request.setAttribute("interestObjId", interestObjId);
		   return mapping.findForward("success");
		}else{
		   return mapping.findForward("failure");
		}
	}
}