/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package struts.FSM.action;

import java.io.IOException;
import java.io.UnsupportedEncodingException;

import hibernate.FSM.FsmFunctionProcess;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import net.sf.hibernate.HibernateException;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import business.FSM.MappingPhase;
import struts.FSM.form.FunctionProcessForm;

/** 
 * MyEclipse Struts
 * Creation date: 01-06-2010
 * 
 * XDoclet definition:
 * @struts.action path="/addFunctionProcess" name="functionProcessForm" scope="request" validate="true"
 * @struts.action-forward name="success" path="/FSM/cosmicStandard/mapping/functionProcess.jsp" contextRelative="true"
 * @struts.action-forward name="failure" path="/FSM/cosmicStandard/failure.jsp" contextRelative="true"
 */
public class AddFunctionProcessAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 * @throws HibernateException 
	 * @throws IOException 
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) throws HibernateException, IOException {
		FunctionProcessForm fm = (FunctionProcessForm) form;// TODO Auto-generated method stub
		MappingPhase mp = new MappingPhase();//业务层函数,对对等组件进行增删改查等操作
		FsmFunctionProcess ffp = new FsmFunctionProcess(); //定义实体Bean
		
		//从form表单将功能流程信息取出，赋给实体bean
		String funcProsName = null;
		String funcProsDesp = null;
		try {
			funcProsName = new String(fm.getFuncProsName().getBytes("ISO-8859-1"),"gb2312");
			funcProsDesp = new String(fm.getFuncProsDesp().getBytes("ISO-8859-1"),"gb2312");
		} catch (UnsupportedEncodingException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		
		
		ffp.setPeerCompId(Integer.valueOf(fm.getPeerCompId()));
		ffp.setFuncProsName(funcProsName);
		ffp.setFuncProsDesp(funcProsDesp);
		ffp.setMeasureStatus(Integer.valueOf(fm.getMeasureStatus()));
		ffp.setMappingEventStatus(0);
		ffp.setMappingIostatus(0);
		ffp.setMappingUserStatus(0);
		
	
		
		/*调用业务层,添加功能流程*/
		boolean result = mp.insertFunctionProcess(ffp);
		if(result==true){
		   return mapping.findForward("success");
		}else{
		   return mapping.findForward("failure");
		}		
	}
}