/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package struts.FSM.action;
import javaBeans.fsm.ProjectMeasureBean;

import hibernate.FSM.FsmFunctionProcess;
import hibernate.FSM.FsmFunctionProcessEvent;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import net.sf.hibernate.HibernateException;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import business.FSM.MappingPhase;
import struts.FSM.form.FunctionProcessEventForm;

/** 
 * MyEclipse Struts
 * Creation date: 03-09-2010
 * 
 * XDoclet definition:
 * @struts.action path="/addFunctionProcessEvent" name="functionProcessEventForm" scope="request" validate="true"
 * @struts.action-forward name="success" path="/FSM/cosmicStandard/mapping/functionProcessEvent.jsp" contextRelative="true"
 * @struts.action-forward name="failure" path="/FSM/cosmicStandard/failure.jsp" contextRelative="true"
 */
public class AddFunctionProcessEventAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 * @throws HibernateException 
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) throws HibernateException {
		FunctionProcessEventForm fpef = (FunctionProcessEventForm) form;// TODO Auto-generated method stub
		MappingPhase mp = new MappingPhase();//业务层函数,对功能流程-事件进行增删改查等操作
		FsmFunctionProcessEvent ffpe = new FsmFunctionProcessEvent(); //定义实体Bean
		
		
		//从form表单将功能流程-事件信息取出，赋给实体bean
		 Integer funcProsId = Integer.valueOf(fpef.getFuncProsId());
		 request.getSession().setAttribute("funcProsId", funcProsId);
		  String eventId[] = fpef.getEventId();
		 for(int i=0; i<eventId.length;i++){
			//将功能流程-事件插入数据库
			 ffpe.setFuncProsId(funcProsId);
			 ffpe.setEventId(Integer.valueOf(eventId[i]));
			 boolean result1 = mp.insertFunctionProcessEvent(ffpe);  
			 if(result1==false){
				 return mapping.findForward("failure");
			 }	
		 }
		 //查找id为funcProsId的功能流程
		 FsmFunctionProcess ffp = (FsmFunctionProcess) mp.getFunctionProcessById(funcProsId);
		 //更改功能流程的MappingEventStatus为1，表示已经完成功能流程-事件的映射
		 ffp.setMappingEventStatus(1);
		 Boolean result2 = mp.updateFunctionProcess(ffp);
		 if(result2==false){
			 return mapping.findForward("failure");
		 }
		 return mapping.findForward("success");
	}
}