/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package struts.FSM.action;

import java.io.UnsupportedEncodingException;

import hibernate.FSM.FsmMeasureScope;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import net.sf.hibernate.HibernateException;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import business.FSM.StrategyPhase;
import struts.FSM.form.MeasureScopeForm;

/** 
 * MyEclipse Struts
 * Creation date: 12-13-2009
 * 
 * XDoclet definition:
 * @struts.action path="/addLayer" name="layerForm" scope="request" validate="true"
 * @struts.action-forward name="success" path="/FSM/cosmicStandard/layerList.jsp" contextRelative="true"
 * @struts.action-forward name="failure" path="/FSM/cosmicStandard/failure.jsp" contextRelative="true"
 */
public class AddMeasureScopeAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 * @throws HibernateException 
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) throws HibernateException {
		MeasureScopeForm measureScopeForm = (MeasureScopeForm) form;// TODO Auto-generated method stub
		StrategyPhase sp = new StrategyPhase();//业务层函数,对度量范围进行增删改查等操作
		FsmMeasureScope fms = new FsmMeasureScope();          //定义实体bean
		
		/*从form表单中获取MeasureScope信息,赋值给实体Bean*/
		String measureScopeName = null;
		String measureScopeDesp = null;
		try {
			measureScopeName = new String(measureScopeForm.getMeasureScopeName().getBytes("ISO-8859-1"),"gb2312");
			measureScopeDesp = new String(measureScopeForm.getMeasureScopeDesp().getBytes("ISO-8859-1"),"gb2312");		
		} catch (UnsupportedEncodingException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
				
		fms.setProductId(new Integer(measureScopeForm.getProductId()));
		fms.setMeasureScopeName(measureScopeName);
		fms.setMeasureScopeDesp(measureScopeDesp);
		
		
		/*调用业务层,添加度量范围*/
		boolean result = sp.insertMeasureScope(fms);
		if(result==true){
		   return mapping.findForward("success");
		}else{
		   return mapping.findForward("failure");
		}
		
		
	
	}
}