/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package struts.FSM.action;

import java.io.IOException;
import java.io.UnsupportedEncodingException;

import hibernate.FSM.FsmReg;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import net.sf.hibernate.HibernateException;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import business.FSM.StrategyPhase;
import business.FSM.UserInfo;
import struts.FSM.form.RegisterForm;

/** 
 * MyEclipse Struts
 * Creation date: 12-13-2009
 * 
 * XDoclet definition:
 * @struts.action path="/addLayer" name="layerForm" scope="request" validate="true"
 * @struts.action-forward name="success" path="/FSM/cosmicStandard/layerList.jsp" contextRelative="true"
 * @struts.action-forward name="failure" path="/FSM/cosmicStandard/failure.jsp" contextRelative="true"
 */
public class AddRegisterAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 * @throws HibernateException 
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) throws HibernateException {
		RegisterForm regForm = (RegisterForm) form;// TODO Auto-generated method stub
		StrategyPhase sp = new StrategyPhase();//业务层函数,对层次进行增删改查等操作
		FsmReg fr = new FsmReg();          //定义实体bean
		
		/*从form表单中获取Register信息,赋值给实体Bean*/
		String userName = new String(regForm.getUsername());
		String password1 = new String(regForm.getPassword1());	
		
		UserInfo ui = new UserInfo();
		Object obj = ui.getUserByName(userName);
		if(obj!=null){
			//return mapping.findForward("failure");
			try {
				response.sendRedirect("/fsm/registerAlert.jsp?success=false");
			} catch (IOException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
		}else{
			fr.setUserName(regForm.getUsername());
			fr.setPassword(regForm.getPassword1());
			
			/*调用业务层,添加层次*/
			boolean result = sp.insertRegister(fr);
			if(result==true){
				try {
					response.sendRedirect("/fsm/registerAlert.jsp?success=true");
				} catch (IOException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
			}else{
				try {
					response.sendRedirect("/fsm/registerAlert.jsp?success=false");
				} catch (IOException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
			}
			
		}
		return null;
		

	}
}