/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */

package struts.FSM.action;

import java.io.UnsupportedEncodingException;

import hibernate.FSM.FsmInterestObject;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import net.sf.hibernate.HibernateException;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import business.FSM.MappingPhase;
import struts.FSM.form.InterestObjectForm;

/** 
 * MyEclipse Struts
 * Creation date: 03-09-2010
 * 
 * XDoclet definition:
 * @struts.action path="/editInterestObject" name="interestObjectForm" scope="request" validate="true"
 * @struts.action-forward name="success" path="/FSM/cosmicStandard/mapping/interestObject.jsp" contextRelative="true"
 * @struts.action-forward name="failure" path="/FSM/cosmicStandard/failure.jsp" contextRelative="true"
 */
public class EditInterestObjectAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 * @throws HibernateException 
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) throws HibernateException {
		//Integer peerCompId = new Integer(request.getParameter("peerCompId"));
		InterestObjectForm interestObjectForm = (InterestObjectForm) form;// TODO Auto-generated method stub
		MappingPhase mp = new MappingPhase();//业务层函数,对兴趣对象进行增删改查等操作
		FsmInterestObject fio = new FsmInterestObject();          //定义实体bean
		
		/*将id为interestObjId的实体bean查找出来*/
		int interestObjId = new Integer(interestObjectForm.getId());
		fio = (FsmInterestObject)mp.getInterestObjectById(interestObjId);
		/*从form表单中获取兴趣对象信息,更新实体Bean*/
		String interestObjName = null;
		String interestObjDesp = null;
		try {
			interestObjName = new String(interestObjectForm.getInterestObjName().getBytes("ISO-8859-1"),"gb2312");
			interestObjDesp = new String(interestObjectForm.getInterestObjDesp().getBytes("ISO-8859-1"),"gb2312");
		} catch (UnsupportedEncodingException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		
		
		fio.setPeerCompId(new Integer(interestObjectForm.getPeerCompId()));
		fio.setInterestObjName(interestObjName);
		fio.setInterestObjDesp(interestObjDesp);
		//fio.setMeasureStatus(new Integer(interestObjectForm.getMeasureStatus()));
		
		
		/*调用业务层,添加兴趣对象*/
		

		boolean result = mp.updateInterestObject(fio);
		if(result==true){
		   request.setAttribute("peerCompId", interestObjectForm.getPeerCompId());//这句的目的是能够转跳回interestObject.jsp
		   return mapping.findForward("success");
		}else{
		   return mapping.findForward("failure");
		}
	}
}