/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package struts.FSM.action;

import java.io.UnsupportedEncodingException;

import hibernate.FSM.FsmLayer;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import net.sf.hibernate.HibernateException;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import business.FSM.StrategyPhase;
import struts.FSM.form.LayerForm;

/** 
 * MyEclipse Struts
 * Creation date: 03-08-2010
 * 
 * XDoclet definition:
 * @struts.action path="/editLayer" name="layerForm" scope="request" validate="true"
 * @struts.action-forward name="success" path="/FSM/cosmicStandard/strategy/layer.jsp" contextRelative="true"
 * @struts.action-forward name="failure" path="/FSM/cosmicStandard/failure.jsp" contextRelative="true"
 */
public class EditLayerAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 * @throws HibernateException 
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) throws HibernateException {
		//Integer peerCompId = new Integer(request.getParameter("peerCompId"));
		LayerForm layerForm = (LayerForm) form;// TODO Auto-generated method stub
		StrategyPhase sp = new StrategyPhase();//业务层函数,对层次进行增删改查等操作
		FsmLayer fl = new FsmLayer();          //定义实体bean
		
		/*将id为layerId的实体bean查找出来*/
		int layerId = new Integer(layerForm.getId());
		fl = (FsmLayer)sp.getLayerById(layerId);
		/*从form表单中获取层次信息,更新实体Bean*/
		String layerName = null;
		String layerDesp = null;
		try {
			layerName = new String(layerForm.getLayerName().getBytes("ISO-8859-1"),"gb2312");
			layerDesp = new String(layerForm.getLayerDesp().getBytes("ISO-8859-1"),"gb2312");
		} catch (UnsupportedEncodingException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		
		
		fl.setProductId(new Integer(layerForm.getProductId()));
		fl.setLayerName(layerName);
		fl.setLayerDesp(layerDesp);
		fl.setMeasureStatus(new Integer(layerForm.getMeasureStatus()));
		
		
		/*调用业务层,添加层次*/		

		boolean result = sp.updateLayer(fl);
		if(result==true){
		   request.setAttribute("productId", layerForm.getProductId());//这句的目的是能够转跳回layer.jsp
		   return mapping.findForward("success");
		}else{
		   return mapping.findForward("failure");
		}
	}
}

