/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */



/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package struts.FSM.action;

import java.io.UnsupportedEncodingException;

import hibernate.FSM.FsmFunctionProcess;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import net.sf.hibernate.HibernateException;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import business.FSM.MappingPhase;
import struts.FSM.form.FunctionProcessForm;

/** 
 * MyEclipse Struts
 * Creation date: 03-08-2010
 * 
 * XDoclet definition:
 * @struts.action path="/editFunctionProcess" name="functionProcessForm" scope="request" validate="true"
 * @struts.action-forward name="success" path="/FSM/cosmicStandard/mapping/functionProcess.jsp" contextRelative="true"
 * @struts.action-forward name="failure" path="/FSM/cosmicStandard/failure.jsp" contextRelative="true"
 */
public class EditFunctionProcessAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 * @throws HibernateException 
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) throws HibernateException {
		//Integer peerCompId = new Integer(request.getParameter("peerCompId"));
		FunctionProcessForm functionProcessForm = (FunctionProcessForm) form;// TODO Auto-generated method stub
		MappingPhase mp = new MappingPhase();//业务层函数,对功能流程进行增删改查等操作
		FsmFunctionProcess ffp = new FsmFunctionProcess();          //定义实体bean
		
		/*将id为funcProsId的实体bean查找出来*/
		int funcProsId = new Integer(functionProcessForm.getId());
		ffp = (FsmFunctionProcess)mp.getFunctionProcessById(funcProsId);
		/*从form表单中获取功能流程信息,更新实体Bean*/
		String funcProsName = null;
		String funcProsDesp = null;
		try {
			funcProsName = new String(functionProcessForm.getFuncProsName().getBytes("ISO-8859-1"),"gb2312");
			funcProsDesp = new String(functionProcessForm.getFuncProsDesp().getBytes("ISO-8859-1"),"gb2312");
		} catch (UnsupportedEncodingException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		
		
		ffp.setPeerCompId(new Integer(functionProcessForm.getPeerCompId()));
		ffp.setFuncProsName(funcProsName);
		ffp.setFuncProsDesp(funcProsDesp);
		ffp.setMeasureStatus(new Integer(functionProcessForm.getMeasureStatus()));
		
		
		/*调用业务层,添加功能流程*/
		

		boolean result = mp.updateFunctionProcess(ffp);
		if(result==true){
		   request.setAttribute("peerCompId", functionProcessForm.getPeerCompId());//这句的目的是能够转跳回functionProcess.jsp
		   return mapping.findForward("success");
		}else{
		   return mapping.findForward("failure");
		}
	}
}