/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package struts.FSM.action;

import java.io.IOException;
import java.io.UnsupportedEncodingException;

import hibernate.FSM.FsmDataGroup;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import net.sf.hibernate.HibernateException;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import business.FSM.MappingPhase;
import struts.FSM.form.DataGroupForm;

/** 
 * MyEclipse Struts
 * Creation date: 01-07-2010
 * 
 * XDoclet definition:
 * @struts.action path="/editDataGroup" name="dataGroupForm" scope="request" validate="true"
 * @struts.action-forward name="success" path="/FSM/cosmicStandard/mapping/addDataGroup.jsp" contextRelative="true"
 * @struts.action-forward name="failure" path="/FSM/cosmicStandard/failure.jsp" contextRelative="true"
 */
public class EditDataGroupAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 * @throws HibernateException 
	 * @throws IOException 
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) throws HibernateException, IOException {
		DataGroupForm dataGroupForm = (DataGroupForm) form;// TODO Auto-generated method stub
		MappingPhase mp = new MappingPhase();//业务层函数,对数据组进行增删改查等操作
		FsmDataGroup fdg = new FsmDataGroup();          //定义实体bean
		
		
		
		/*将id为dataGroupId的实体bean查找出来*/
		int dataGroupId = new Integer(dataGroupForm.getId());
		fdg = (FsmDataGroup)mp.getDataGroupById(dataGroupId);
		/*从form表单中获取数据组信息,更新实体Bean*/
		String dataGroupName = null;
		String dataGroupDesp = null;
		try {
			dataGroupName = new String(dataGroupForm.getDataGroupName().getBytes("ISO-8859-1"),"gb2312");
			dataGroupDesp = new String(dataGroupForm.getDataGroupDesp().getBytes("ISO-8859-1"),"gb2312");
		} catch (UnsupportedEncodingException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}		
		fdg.setInterestObjId(new Integer(dataGroupForm.getInterestObjId()));
		fdg.setDataGroupName(dataGroupName);
		fdg.setDataGroupDesp(dataGroupDesp);		
		
		/*调用业务层,添加数据组*/		
		boolean result = mp.updateDataGroup(fdg);
		if(result==true){
			//这些目的是能够转跳回addDataGroup.jsp
			request.setAttribute("interestObjId", dataGroupForm.getInterestObjId());
			
		    return mapping.findForward("success");
		  
		}else{
		   return mapping.findForward("failure");
		}
	}
}