/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package struts.FSM.action;
import javaBeans.fsm.ProjectMeasureBean;

import hibernate.FSM.FsmFunctionProcess;
import hibernate.FSM.FsmFunctionProcessEvent;
import hibernate.FSM.FsmFunctionProcessUser;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import net.sf.hibernate.HibernateException;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import business.FSM.MappingPhase;
import struts.FSM.form.FunctionProcessEventForm;
import struts.FSM.form.FunctionProcessUserForm;

/** 
 * MyEclipse Struts
 * Creation date: 03-09-2010
 * 
 * XDoclet definition:
 * @struts.action path="/addFunctionProcessEvent" name="functionProcessEventForm" scope="request" validate="true"
 * @struts.action-forward name="success" path="/FSM/cosmicStandard/mapping/functionProcessEvent.jsp" contextRelative="true"
 * @struts.action-forward name="failure" path="/FSM/cosmicStandard/failure.jsp" contextRelative="true"
 */
public class AddFunctionProcessUserAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 * @throws HibernateException 
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) throws HibernateException {
		FunctionProcessUserForm fpuf = (FunctionProcessUserForm) form;// TODO Auto-generated method stub
		MappingPhase mp = new MappingPhase();//业务层函数,对功能流程-用户进行增删改查等操作
		FsmFunctionProcessUser ffpu = new FsmFunctionProcessUser(); //定义实体Bean
		
		
		//从form表单将功能流程-用户信息取出，赋给实体bean
		 Integer funcProsId = Integer.valueOf(fpuf.getFuncProsId());
		 request.getSession().setAttribute("funcProsId", funcProsId);
		  String userId[] = fpuf.getUserId();
		 for(int i=0; i<userId.length;i++){
			//将功能流程-用户插入数据库
			 ffpu.setFuncProsId(funcProsId);
			 ffpu.setUserId(Integer.valueOf(userId[i]));
			 boolean result1 = mp.insertFunctionProcessUser(ffpu);  
			 if(result1==false){
				 return mapping.findForward("failure");
			 }	
		 }
		 //查找id为funcProsId的功能流程
		 FsmFunctionProcess ffp = (FsmFunctionProcess) mp.getFunctionProcessById(funcProsId);
		 //更改功能流程的MappingUserStatus为1，表示已经完成功能流程-用户的映射
		 ffp.setMappingUserStatus(1);
		 Boolean result2 = mp.updateFunctionProcess(ffp);
		 if(result2==false){
			 return mapping.findForward("failure");
		 }
		 return mapping.findForward("success");
	}
}