/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package struts.FSM.action;

import java.io.UnsupportedEncodingException;

import hibernate.FSM.FsmUser;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import net.sf.hibernate.HibernateException;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import business.FSM.StrategyPhase;
import struts.FSM.form.UserForm;

/** 
 * MyEclipse Struts
 * Creation date: 03-10-2010
 * 
 * XDoclet definition:
 * @struts.action path="/addFunctionUser" name="userForm" scope="request" validate="true"
 * @struts.action-forward name="success" path="/FSM/cosmicStandard/strategy/functionUser.jsp" contextRelative="true"
 * @struts.action-forward name="failure" path="/FSM/cosmicStandard/failure.jsp" contextRelative="true"
 */
public class AddFunctionUserAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 * @throws HibernateException 
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) throws HibernateException {
		UserForm userForm = (UserForm) form;// TODO Auto-generated method stub
		StrategyPhase sp = new StrategyPhase();//业务层函数,对功能用户进行增删改查等操作
		FsmUser fu = new FsmUser();          //定义实体bean
		
		/*从form表单中获取User信息,赋值给实体Bean*/
		String userName = null;
		String userDesp = null;
		try {
			userName = new String(userForm.getUserName().getBytes("ISO-8859-1"),"gb2312");
			userDesp = new String(userForm.getUserDesp().getBytes("ISO-8859-1"),"gb2312");
		} catch (UnsupportedEncodingException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		
		
		fu.setProductId(new Integer(userForm.getProductId()));
		fu.setUserName(userName);
		fu.setUserDesp(userDesp);
		
		
		/*调用业务层,添加功能用户*/
		boolean result = sp.insertFunctionUser(fu);
		if(result==true){
		   return mapping.findForward("success");
		}else{
		   return mapping.findForward("failure");
		}
		
		
	
	}
}