/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package struts.FSM.action;

import java.io.UnsupportedEncodingException;

import hibernate.FSM.FsmFunctionProcess;
import hibernate.FSM.FsmInterestObject;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import net.sf.hibernate.HibernateException;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import business.FSM.MappingPhase;
import struts.FSM.form.InterestObjectForm;

/** 
 * MyEclipse Struts
 * Creation date: 01-06-2010
 * 
 * XDoclet definition:
 * @struts.action path="/addInterestObject" name="interestObjectForm" scope="request" validate="true"
 */
public class AddInterestObjectAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 * @throws HibernateException 
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) throws HibernateException {
		InterestObjectForm fm = (InterestObjectForm) form;// TODO Auto-generated method stub
		MappingPhase mp = new MappingPhase();//业务层函数,对兴趣对象进行增删改查等操作
		FsmInterestObject fio = new FsmInterestObject(); //定义实体Bean
		
		//从form表单将功能流程信息取出，赋给实体bean
		String interestObjName = null;
		String interestObjDesp = null;
		try {
			interestObjName = new String(fm.getInterestObjName().getBytes("ISO-8859-1"),"gb2312");
			interestObjDesp = new String(fm.getInterestObjDesp().getBytes("ISO-8859-1"),"gb2312");
		} catch (UnsupportedEncodingException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		
		
		fio.setPeerCompId(Integer.valueOf(fm.getPeerCompId()));
		fio.setInterestObjName(interestObjName);
		fio.setInterestObjDesp(interestObjDesp);
		
		/*调用业务层,添加功能流程*/
		boolean result = mp.insertInterestObject(fio);
		if(result==true){
		   return mapping.findForward("success");
		}else{
		   return mapping.findForward("failure");
		}
	}
}