/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package struts.FSM.action;

import java.io.UnsupportedEncodingException;
import java.sql.Date;
import hibernate.FSM.FsmProduct;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import net.sf.hibernate.HibernateException;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import business.FSM.ProductMeasureBusiness;
import business.FSM.UserInfo;
import struts.FSM.form.ProductForm;

/** 
 * MyEclipse Struts
 * Creation date: 12-13-2009
 * 
 * XDoclet definition:
 * @struts.action path="/addProductAction" name="productForm" scope="request" validate="true"
 */
public class AddProductAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 * @throws HibernateException 
	 */
	/*
	 * 增加产品信息
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) throws HibernateException {
		
		ProductForm productForm = (ProductForm) form;// TODO Auto-generated method stub
		
		ProductMeasureBusiness pmb = new ProductMeasureBusiness();//业务层函数，对带估算软件进行操作如增删改查等
		//实体bean
		FsmProduct fp = new FsmProduct();
	
		String userName = (String)request.getSession().getAttribute("userName");
		int regId = UserInfo.getRegIdByUserName(userName);
		
		
		//用于接受汉字内容的转换
		String productName = null;
		String productDesp = null;
		String estimator = null;
		String startTime = null;
		String endTime = null;
		String estimateStartTime = null;
		String estimateEndTime = null;
		try {
			productName = new String(productForm.getProductName().getBytes("ISO-8859-1"),"gb2312");
			productDesp = new String(productForm.getProductDesp().getBytes("ISO-8859-1"),"gb2312");
			estimator = new String(productForm.getEstimator().getBytes("ISO-8859-1"),"gb2312");
			startTime = new String(productForm.getStartTime().getBytes("ISO-8859-1"),"gb2312");			
			endTime = new String(productForm.getEndTime().getBytes("ISO-8859-1"),"gb2312");
			estimateStartTime = new String(productForm.getEstimateStartTime().getBytes("ISO-8859-1"),"gb2312");
			estimateEndTime = new String(productForm.getEstimateEndTime().getBytes("ISO-8859-1"),"gb2312");
		} catch (UnsupportedEncodingException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		
		//从form表单中获取Product信息,赋值给实体Bean
		fp.setProductName(productName);
		fp.setProductDesp(productDesp);
		fp.setProductType(Integer.valueOf(productForm.getProductType()));
		fp.setDevelopType(Integer.valueOf(productForm.getDevelopType()));
		fp.setMeasureMethod(Integer.valueOf(productForm.getMeasureMethod()));
		fp.setLifecyclePhase(Integer.valueOf(productForm.getLifecyclePhase()));
		fp.setMeasureStatus(Integer.valueOf(productForm.getMeasureStatus()));
		fp.setEstimator(estimator);
		fp.setStartTime(Date.valueOf(startTime));
		fp.setEndTime(Date.valueOf(endTime));
		fp.setEstimateStartTime(Date.valueOf(estimateStartTime));
		fp.setEstimateEndTime(Date.valueOf(estimateEndTime));
		fp.setRegId(regId);
		//调用业务层函数增加待估算软件
		boolean result = pmb.insertProduct(fp);
		if(result==true){
		   return mapping.findForward("success");
		}else{
		   return mapping.findForward("failure");
		}
	}
}