/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */

package struts.FSM.action;

import java.io.UnsupportedEncodingException;

import hibernate.FSM.FsmEvent;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import net.sf.hibernate.HibernateException;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import business.FSM.MappingPhase;
import struts.FSM.form.EventForm;

/** 
 * MyEclipse Struts
 * Creation date: 03-09-2010
 * 
 * XDoclet definition:
 * @struts.action path="/editEvent" name="eventForm" scope="request" validate="true"
 * @struts.action-forward name="success" path="/FSM/cosmicStandard/mapping/event.jsp" contextRelative="true"
 * @struts.action-forward name="failure" path="/FSM/cosmicStandard/failure.jsp" contextRelative="true"
 */
public class EditEventAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 * @throws HibernateException 
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) throws HibernateException {
		//Integer peerCompId = new Integer(request.getParameter("peerCompId"));
		EventForm eventForm = (EventForm) form;// TODO Auto-generated method stub
		MappingPhase mp = new MappingPhase();//业务层函数,对事件进行增删改查等操作
		FsmEvent fe = new FsmEvent();          //定义实体bean
		
		/*将id为eventId的实体bean查找出来*/
		int eventId = new Integer(eventForm.getId());
		fe = (FsmEvent)mp.getEventById(eventId);
		
		/*从form表单中获取事件信息,更新实体Bean*/
		String eventName = null;
		String eventDesp = null;
		try {
			eventName = new String(eventForm.getEventName().getBytes("ISO-8859-1"),"gb2312");
			eventDesp = new String(eventForm.getEventDesp().getBytes("ISO-8859-1"),"gb2312");
		} catch (UnsupportedEncodingException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		
		
		fe.setPeerCompId(new Integer(eventForm.getPeerCompId()));
		fe.setEventName(eventName);
		fe.setEventDesp(eventDesp);
		
		
		
		/*调用业务层,添加事件*/
		

		boolean result = mp.updateEvent(fe);
		if(result==true){
		   request.setAttribute("peerCompId", eventForm.getPeerCompId());//这句的目的是能够转跳回event.jsp
		   return mapping.findForward("success");
		}else{
		   return mapping.findForward("failure");
		}
	}
}