/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package struts.FSM.action;

import java.io.UnsupportedEncodingException;

import hibernate.FSM.FsmMeasureScope;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import net.sf.hibernate.HibernateException;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import business.FSM.StrategyPhase;
import struts.FSM.form.MeasureScopeForm;

/** 
 * MyEclipse Struts
 * Creation date: 03-08-2010
 * 
 * XDoclet definition:
 * @struts.action path="/editLayer" name="layerForm" scope="request" validate="true"
 * @struts.action-forward name="success" path="/FSM/cosmicStandard/strategy/layer.jsp" contextRelative="true"
 * @struts.action-forward name="failure" path="/FSM/cosmicStandard/failure.jsp" contextRelative="true"
 */
public class EditMeasureScopeAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 * @throws HibernateException 
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) throws HibernateException {
		//Integer peerCompId = new Integer(request.getParameter("peerCompId"));
		MeasureScopeForm measureScopeForm = (MeasureScopeForm) form;// TODO Auto-generated method stub
		StrategyPhase sp = new StrategyPhase();//业务层函数,对度量范围进行增删改查等操作
		FsmMeasureScope fms = new FsmMeasureScope();          //定义实体bean
		
		/*将id为measScopeId的实体bean查找出来*/
		int measScopeId = new Integer(measureScopeForm.getId());
		fms = (FsmMeasureScope)sp.getMeasureScopeById(measScopeId);
		/*从form表单中获取度量范围信息,更新实体Bean*/
		String measureScopeName = null;
		String measureScopeDesp = null;
		try {
			measureScopeName = new String(measureScopeForm.getMeasureScopeName().getBytes("ISO-8859-1"),"gb2312");
			measureScopeDesp = new String(measureScopeForm.getMeasureScopeDesp().getBytes("ISO-8859-1"),"gb2312");
		} catch (UnsupportedEncodingException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		fms.setProductId(new Integer(measureScopeForm.getProductId()));
		fms.setMeasureScopeName(measureScopeName);
		fms.setMeasureScopeDesp(measureScopeDesp);		
		
		
		/*调用业务层,修改度量范围*/		

		boolean result = sp.updateMeasureScope(fms);
		if(result==true){
		   request.setAttribute("productId", measureScopeForm.getProductId());//这句的目的是能够转跳回measurePurpose.jsp
		   return mapping.findForward("success");
		}else{
		   return mapping.findForward("failure");
		}
	}
}

