/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package struts.FSM.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 01-07-2010
 * 
 * XDoclet definition:
 * @struts.form name="dataAttributeForm"
 */
public class DataAttributeForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** dataGroupId property */
	private String dataGroupId;

	/** dataAttriDesp property */
	private String dataAttriDesp;

	/** id property */
	private String id;

	/** dataAttriName property */
	private String dataAttriName;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the dataGroupId.
	 * @return String
	 */
	public String getDataGroupId() {
		return dataGroupId;
	}

	/** 
	 * Set the dataGroupId.
	 * @param dataGroupId The dataGroupId to set
	 */
	public void setDataGroupId(String dataGroupId) {
		this.dataGroupId = dataGroupId;
	}

	/** 
	 * Returns the dataAttriDesp.
	 * @return String
	 */
	public String getDataAttriDesp() {
		return dataAttriDesp;
	}

	/** 
	 * Set the dataAttriDesp.
	 * @param dataAttriDesp The dataAttriDesp to set
	 */
	public void setDataAttriDesp(String dataAttriDesp) {
		this.dataAttriDesp = dataAttriDesp;
	}

	/** 
	 * Returns the id.
	 * @return String
	 */
	public String getId() {
		return id;
	}

	/** 
	 * Set the id.
	 * @param id The id to set
	 */
	public void setId(String id) {
		this.id = id;
	}

	/** 
	 * Returns the dataAttriName.
	 * @return String
	 */
	public String getDataAttriName() {
		return dataAttriName;
	}

	/** 
	 * Set the dataAttriName.
	 * @param dataAttriName The dataAttriName to set
	 */
	public void setDataAttriName(String dataAttriName) {
		this.dataAttriName = dataAttriName;
	}
}