/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package struts.FSM.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 04-25-2010
 * 
 * XDoclet definition:
 * @struts.form name="measureScopeForm"
 */
public class MeasureScopeForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** productId property */
	private String productId;

	/** measureScopeName property */
	private String measureScopeName;

	/** id property */
	private String id;

	/** measureScopeDesp property */
	private String measureScopeDesp;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the productId.
	 * @return String
	 */
	public String getProductId() {
		return productId;
	}

	/** 
	 * Set the productId.
	 * @param productId The productId to set
	 */
	public void setProductId(String productId) {
		this.productId = productId;
	}

	/** 
	 * Returns the measureScopeName.
	 * @return String
	 */
	public String getMeasureScopeName() {
		return measureScopeName;
	}

	/** 
	 * Set the measureScopeName.
	 * @param measureScopeName The measureScopeName to set
	 */
	public void setMeasureScopeName(String measureScopeName) {
		this.measureScopeName = measureScopeName;
	}

	/** 
	 * Returns the id.
	 * @return String
	 */
	public String getId() {
		return id;
	}

	/** 
	 * Set the id.
	 * @param id The id to set
	 */
	public void setId(String id) {
		this.id = id;
	}

	/** 
	 * Returns the measureScopeDesp.
	 * @return String
	 */
	public String getMeasureScopeDesp() {
		return measureScopeDesp;
	}

	/** 
	 * Set the measureScopeDesp.
	 * @param measureScopeDesp The measureScopeDesp to set
	 */
	public void setMeasureScopeDesp(String measureScopeDesp) {
		this.measureScopeDesp = measureScopeDesp;
	}
}