/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package struts.FSM.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 12-14-2009
 * 
 * XDoclet definition:
 * @struts.form name="peerComponentForm"
 */
public class PeerComponentForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** measureStatus property */
	private String measureStatus;

	/** peerCompName property */
	private String peerCompName;

	/** peerCompDesp property */
	private String peerCompDesp;

	/** compType property */
	private String compType;

	/** id property */
	private String id;

	private String layerId;
	
	private String fatherId;
	
	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the measureStatus.
	 * @return String
	 */
	public String getMeasureStatus() {
		return measureStatus;
	}

	/** 
	 * Set the measureStatus.
	 * @param measureStatus The measureStatus to set
	 */
	public void setMeasureStatus(String measureStatus) {
		this.measureStatus = measureStatus;
	}

	/** 
	 * Returns the peerCompName.
	 * @return String
	 */
	public String getPeerCompName() {
		return peerCompName;
	}

	/** 
	 * Set the peerCompName.
	 * @param peerCompName The peerCompName to set
	 */
	public void setPeerCompName(String peerCompName) {
		this.peerCompName = peerCompName;
	}

	/** 
	 * Returns the peerCompDesp.
	 * @return String
	 */
	public String getPeerCompDesp() {
		return peerCompDesp;
	}

	/** 
	 * Set the peerCompDesp.
	 * @param peerCompDesp The peerCompDesp to set
	 */
	public void setPeerCompDesp(String peerCompDesp) {
		this.peerCompDesp = peerCompDesp;
	}

	/** 
	 * Returns the compType.
	 * @return String
	 */
	public String getCompType() {
		return compType;
	}

	/** 
	 * Set the compType.
	 * @param compType The compType to set
	 */
	public void setCompType(String compType) {
		this.compType = compType;
	}

	/** 
	 * Returns the id.
	 * @return String
	 */
	public String getId() {
		return id;
	}

	/** 
	 * Set the id.
	 * @param id The id to set
	 */
	public void setId(String id) {
		this.id = id;
	}
	
	public String getLayerId() {
		return layerId;
	}

	/** 
	 * Set the id.
	 * @param id The id to set
	 */
	public void setLayerId(String layerId) {
		this.layerId = layerId;
	}

	public String getFatherId() {
		return fatherId;
	}

	public void setFatherId(String fatherId) {
		this.fatherId = fatherId;
	}
}