/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package struts.FSM.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 04-01-2010
 * 
 * XDoclet definition:
 * @struts.form name="productForm"
 */
public class ProductForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** measureStatus property */
	private String measureStatus;

	/** estimateEndTime property */
	private String estimateEndTime;

	/** lifecyclePhase property */
	private String lifecyclePhase;

	/** productName property */
	private String productName;

	/** estimateStartTime property */
	private String estimateStartTime;

	/** id property */
	private String id;

	/** endTime property */
	private String endTime;

	/** productType property */
	private String productType;

	/** productDesp property */
	private String productDesp;

	/** measureMethod property */
	private String measureMethod;

	/** developType property */
	private String developType;

	/** estimator property */
	private String estimator;

	/** startTime property */
	private String startTime;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the measureStatus.
	 * @return String
	 */
	public String getMeasureStatus() {
		return measureStatus;
	}

	/** 
	 * Set the measureStatus.
	 * @param measureStatus The measureStatus to set
	 */
	public void setMeasureStatus(String measureStatus) {
		this.measureStatus = measureStatus;
	}

	/** 
	 * Returns the estimateEndTime.
	 * @return String
	 */
	public String getEstimateEndTime() {
		return estimateEndTime;
	}

	/** 
	 * Set the estimateEndTime.
	 * @param estimateEndTime The estimateEndTime to set
	 */
	public void setEstimateEndTime(String estimateEndTime) {
		this.estimateEndTime = estimateEndTime;
	}

	/** 
	 * Returns the lifecyclePhase.
	 * @return String
	 */
	public String getLifecyclePhase() {
		return lifecyclePhase;
	}

	/** 
	 * Set the lifecyclePhase.
	 * @param lifecyclePhase The lifecyclePhase to set
	 */
	public void setLifecyclePhase(String lifecyclePhase) {
		this.lifecyclePhase = lifecyclePhase;
	}

	/** 
	 * Returns the productName.
	 * @return String
	 */
	public String getProductName() {
		return productName;
	}

	/** 
	 * Set the productName.
	 * @param productName The productName to set
	 */
	public void setProductName(String productName) {
		this.productName = productName;
	}

	/** 
	 * Returns the estimateStartTime.
	 * @return String
	 */
	public String getEstimateStartTime() {
		return estimateStartTime;
	}

	/** 
	 * Set the estimateStartTime.
	 * @param estimateStartTime The estimateStartTime to set
	 */
	public void setEstimateStartTime(String estimateStartTime) {
		this.estimateStartTime = estimateStartTime;
	}

	/** 
	 * Returns the id.
	 * @return String
	 */
	public String getId() {
		return id;
	}

	/** 
	 * Set the id.
	 * @param id The id to set
	 */
	public void setId(String id) {
		this.id = id;
	}

	/** 
	 * Returns the endTime.
	 * @return String
	 */
	public String getEndTime() {
		return endTime;
	}

	/** 
	 * Set the endTime.
	 * @param endTime The endTime to set
	 */
	public void setEndTime(String endTime) {
		this.endTime = endTime;
	}

	/** 
	 * Returns the productType.
	 * @return String
	 */
	public String getProductType() {
		return productType;
	}

	/** 
	 * Set the productType.
	 * @param productType The productType to set
	 */
	public void setProductType(String productType) {
		this.productType = productType;
	}

	/** 
	 * Returns the productDesp.
	 * @return String
	 */
	public String getProductDesp() {
		return productDesp;
	}

	/** 
	 * Set the productDesp.
	 * @param productDesp The productDesp to set
	 */
	public void setProductDesp(String productDesp) {
		this.productDesp = productDesp;
	}

	/** 
	 * Returns the measureMethod.
	 * @return String
	 */
	public String getMeasureMethod() {
		return measureMethod;
	}

	/** 
	 * Set the measureMethod.
	 * @param measureMethod The measureMethod to set
	 */
	public void setMeasureMethod(String measureMethod) {
		this.measureMethod = measureMethod;
	}

	/** 
	 * Returns the developType.
	 * @return String
	 */
	public String getDevelopType() {
		return developType;
	}

	/** 
	 * Set the developType.
	 * @param developType The developType to set
	 */
	public void setDevelopType(String developType) {
		this.developType = developType;
	}

	/** 
	 * Returns the estimator.
	 * @return String
	 */
	public String getEstimator() {
		return estimator;
	}

	/** 
	 * Set the estimator.
	 * @param estimator The estimator to set
	 */
	public void setEstimator(String estimator) {
		this.estimator = estimator;
	}

	/** 
	 * Returns the startTime.
	 * @return String
	 */
	public String getStartTime() {
		return startTime;
	}

	/** 
	 * Set the startTime.
	 * @param startTime The startTime to set
	 */
	public void setStartTime(String startTime) {
		this.startTime = startTime;
	}
}